.catalog:
  name: "purestorafe"
  version: "1.0.0"
  description: "Pure Storage Docker Volume Plugin"
  questions:
    - variable: "DEBUG_ENABLED"
      description: "Enable debugging output in logs"
      label: "Debug Logging"
      required: false
      default: false
      type: "boolean"

    # Pure Storage FlashArray settings
    - variable: "API"
      description: "Example: bcbdab78-d118-1c8d-9310-63d801f4069d"
      label: "API Token for FlashArray"
      required: true
      type: "string"

    - variable: "ENDPOINT"
      description: "Management Endpoint: IP address or FQDN"
      label: "VIP"
      required: true
      type: "string"

    - variable: "DEFAULT_VOL_SZ"
      description: "Volume size (in GiB)"
      label: "Default Volume Size"
      required: true
      default: 1
      type: "int"

    - variable: "VOLUME_DRIVER_NAME"
      description: "Name to use for this plugin instance with Docker:  docker volume create -d <volume driver name>"
      label: "Volume Driver Name"
      required: true
      default: "pure"
      type: "string"

purestorage-fa:
  labels:
    io.rancher.scheduler.global: 'true'
  metadata:
    version: 1
    storageDriverName: "purestorage-fa"
    debug: true
    storagePrefix: "${STORAGE_PREFIX}"
    Endpoint: "${ENDPOINT}"
    API: "${API}"
    DefaultVolSz: ${DEFAULT_VOL_SZ}
    volumeDriverName: "${VOLUME_DRIVER_NAME}"
  storage_driver:
    name: "${VOLUME_DRIVER_NAME}"
    scope: environment
    volume_access_mode: singleHostRW

